// <auto-generated />
namespace Belajar_CRUD_WPF_Dionisius.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addTableTransactionItemNew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTableTransactionItemNew));
        
        string IMigrationMetadata.Id
        {
            get { return "202010211041163_addTableTransactionItemNew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
